front:
  build: .
  container_name: front
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
    - redis:redis
#    - solr:solr
#    - mongo:mongo
#    - memcached:memcached
#    - elasticsearch:elasticsearch
#    - rabbitmq:rabbitmq
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

mysql:
  image: mysql
  container_name: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - ./storage/mysql/data:/var/lib/mysql

redis:
  image: redis
  container_name: redis
  ports:
    - "6379:6379"

#solr:
#  image: solr
#  container_name: solr
#  ports:
#    - "27017:27017"

#mongo:
#  image: mongo
#  container_name: mongo
#  ports:
#    - "27017:27017"

#memcached:
#  image: memcached
#  container_name: memcached
#  ports:
#    - "11211:11211"

#elasticsearch:
#  image: elasticsearch
#  container_name: elasticsearch
#  ports:
#    - "9200:9200"
#    - "9300:9300"

#rabbitmq:
#  image: rabbitmq:3.6.1-management
#  container_name: rabbitmq
#  ports:
#    - "15672:15672"
#    - "5672:5672"
